import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Heading from '../components/heading/Heading';
import Icon from '../components/icon/Icon';
import Link from '../components/link/Link';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main></main>
    </div>
  );
};

export default Home;
